import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AuthProvider, ToasterProvider } from "@src/context";
import { LoadingModal } from "@src/components/modal";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
   return (
      <html lang="en" data-theme="light">
         <body className={inter.className}>
            <AuthProvider>
               <ToasterProvider>
                  <LoadingModal>{children}</LoadingModal>
               </ToasterProvider>
            </AuthProvider>
         </body>
      </html>
   );
}
